### ISSUE TITLE
resque_solo does not play well with scheduled jobs

### ISSUE THREAD

**Issue by rhymes** [neighborland/resque_solo#11]
Hi,

I am using https://github.com/wanelo/counter-cache to schedule counting jobs that get enqueued automatically after a few actions. Unfortunately counter-cache is not smart in the sense that it doesn't detect if a job is already in the queue, hence why I started using resque_solo which works perfectly for "immediate" counting jobs, it does not work with schedule ones. 

As you can see:

![screen shot 2016-11-15 at 11 11 25 am](https://cloud.githubusercontent.com/assets/146201/20301617/4a4ce40e-ab24-11e6-9927-e059a71fa15e.png)

some of these jobs have the same signature and same timestamp. I'd argue that jobs with the same timestamp and signature should not be in the queue at the same time, correct?

Thank you

**Comment by teeparham** [comment]
How is your `CounterCacheJob` configured?

**Comment by rhymes** [comment]
@teeparham sorry, I forgot to add that:

```ruby
class CounterCacheJob
  include Resque::Plugins::UniqueJob

  @queue = :counter_cache

  # adapted from https://github.com/wanelo/counter-cache#default_worker_adapter
  def self.perform(base_class, options)
    options.symbolize_keys!
    options[:source_object_class_name] = base_class.constantize
    # options[:counter] is the class name of the counter that called the adapter
    counter_class = options[:counter].constantize
    counter = counter_class.new(nil, options)
    counter.save!
  end
end
```

**Comment by teeparham** [comment]
That looks like your job is configured OK. I suspect that the jobs are scheduled, but they are not enqueued until the scheduler runs. At that time, `resque_solo` will check the queue and either enqueue the job or not. I don't think there's any issue with this gem. If you want to prevent scheduling duplicate jobs, that's up to whatever you're using to schedule jobs.

**Comment by rhymes** [comment]
@teeparham I'm using https://github.com/resque/resque-scheduler - you're probably right, it makes sense because the scheduler can enqueue the jobs ONLY when they need to be executed
