### ISSUE TITLE
Compatibility with ResqueMailer

### ISSUE THREAD

**Issue by jwg2s** [neighborland/resque_solo#12]
Wanted to reach out and see if anyone has used `resque-solo` in combination with https://github.com/zapnap/resque_mailer?

We're considering adding `resque-solo` into our stack - no obvious issues comes to mind, but my knowledge of resque is admittedly shallow.

**Comment by teeparham** [comment]
We use it with `resque_mailer` on rails 4.2.x. I have not seen any problems.
