### ISSUE TITLE
Jobs aren't being queued

### ISSUE THREAD

**Issue by adambedford** [neighborland/resque_solo#4]
When `Resque::Plugins::UniqueJob` is included in my job class, the job doesn't get queued at all. Initially I thought this was a potential conflict with Resque Retry, but I've removed that for testing purposes and the jobs still don't get queued. 

I'm using Resque in conjunction with the following plugins:

```ruby
gem 'resque_solo'
gem 'resque-pool'
gem 'resque-retry'
gem 'resque-scheduler'
gem 'resque-web'
gem 'resque-scheduler-web'
```

My job looks like this:

```ruby
class AgentCheckJob
  include Resque::Plugins::UniqueJob

  @queue = :check

  # Given an Agent id, load the Agent, call #check on it, and then save it with an updated `last_check_at` timestamp.
  def self.perform(agent_id)
    agent = Agent.find_by(id: agent_id)
    return unless agent

    begin
      return if agent.unavailable?
      agent.log "Checking: #{agent.name}"

      agent.check
      agent.last_check_at = Time.now
      agent.save!

      agent.log "Done: #{agent.name}"
    rescue => e
      agent.error "Exception during check. #{e.message}: #{e.backtrace.join("\n")}"
      raise
    end
  end
end
```

**Comment by teeparham** [comment]
I'm just guessing., but maybe there's a conflict with `resque-pool`. We use the `resque-multi-job-forks` gem, which does a similar thing.

**Comment by adambedford** [comment]
Turns out there was an autoloading exception being swallowed and the job just appeared to not be running.

The good news is that I have this working nicely with `resque-pool`, and now `resque-multi-job-forks` too!
